# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0002_auto_20171130_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('rate', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='authorNmae',
            new_name='authorName',
        ),
    ]
