# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0004_deadlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlines',
            name='date',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
