# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0005_auto_20171201_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
