# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0006_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
