# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0002_deadline'),
        ('SAM2018', '0007_auto_20171201_0352'),
    ]

    operations = [
    ]
