# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0008_merge_20171201_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAM2018.Report'),
        ),
    ]
