# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0009_review_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAM2018.Paper'),
        ),
    ]
