# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0010_report_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifcationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameID', models.CharField(max_length=60, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
