# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0012_favoritepaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepaper',
            name='paper',
        ),
        migrations.AddField(
            model_name='favoritepaper',
            name='papers',
            field=models.ManyToManyField(to='SAM2018.Paper'),
        ),
    ]
