# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0014_auto_20171202_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcation',
            name='notiftemp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAM2018.NotifcationTemp'),
        ),
    ]
