# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAM2018', '0018_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcation',
            name='AllReviewPaper',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
